### ISSUE TITLE
Bad image src

### ISSUE THREAD

**Issue by idmontie** [gios-asu/gios-timeline#8]
The following image in our data file does not resolve? http://www.asu.edu/vppa/specialevents/images/darci/solar_invite.jpg

**Comment by chasethenag420** [comment]
Few more
https://asunow.asu.edu/files/imagecache/story_main_image/image_1.jpeg
https://asunow.asu.edu/files/imagecache/story_main_image/1012.football-cu-0008.jpg
https://asunow.asu.edu/files/imagecache/story_main_image/climateneutrality.jpeg
https://asunow.asu.edu/files/imagecache/story_main_image/wells_fargo_arena_north_1b_0.jpg
https://asunow.asu.edu/files/imagecache/story_main_image/dumpster-dive-asu.jpg
https://asunow.asu.edu/files/imagecache/story_main_image/karen-kao-sustainability-convocation-052.jpg
https://schoolofsustainability.asu.edu/images/content/resident-community-groupshot.jpg

**Comment by chasethenag420** [comment]
I couldn't find these images rest are fixed and uploaded to github to serve form gh pages.

https://asunow.asu.edu/files/imagecache/story_main_image/image_1.jpeg

http://www.asu.edu/vppa/specialevents/images/darci/solar_invite.jpg

**Comment by chasethenag420** [comment]
All these images are existing existing but with different name so we do not need any of these. I am going to delete the image files I uploaded. We can close this issue.
